---
blueprint_id: <%= Blueprint.find_by!(name: bp_batch['name']).id %>
name: Media Transcoding
body: |
  A batch processing application that transcodes videos to different formats
  and resolutions.
concrete_components:
- component_type: job-manager
  name: Job Manager
  body: |
    Specific things about the job manager
  slo_sets:
  - availability:
      "$gte": '0.995'
    costs:
      "$lte": '200'
      currency: "$"
      interval: month
- component_type: object-store
  name: Job Data Store
  body: |
    Specific things about this object store. Maybe S3. Or Riak.
  slo_sets:
  - availability:
      "$gte": '0.995'
- component_type: message-queue
  name: Message Queue
  body: |
    Specific things about the message queue. Probably RabbitMQ.
  slo_sets:
  - availability:
      "$gte": '0.9995'
- component_type: worker-node
  name: Transcoder
  body: |
    Specific things about the transcoding worker.
  slo_sets:
  - availability:
      "$gte": '0.95'
